name: CI Pipeline

# Uruchamiaj workflow przy pushu i pull requestach do main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Definicja zadania
jobs:
  build:
    runs-on: ubuntu-24.04  # Wykorzystaj Ubuntu 24.04

    steps:
    # 1. Sprawdź kod z repozytorium
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Skonfiguruj środowisko Pythona
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Utwórz wirtualne środowisko i zainstaluj zależności
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Wykonaj testy
    - name: Run Tests
      run: |
        echo "Run tests"

    # 5. Zbuduj obraz Dockera
    - name: Build Docker image
      run: docker build -t flask-app:latest .

    # 6. Zaloguj się do GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GITHUB_ACTOR }}  # GitHub user
        password: ${{ secrets.GHCR_TOKEN }}  # Personal Access Token for GHCR

    # 7. Ztaguj obraz Dockera
    - name: Tag Docker image
      run: |
        docker tag flask-app:latest ghcr.io/${{ github.repository_owner }}/flask-app:latest

    # 8. Wypchnij obraz Dockera do GitHub Container Registry
    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/flask-app:latest
