name: CI Pipeline

# Uruchamiaj workflow przy pushu i pull requestach do main
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

# Definicja zadania
jobs:
  build:
    runs-on: ubuntu-24.04  # Wykorzystaj Ubuntu 24.04

    steps:
    # 1. Sprawdź kod z repozytorium
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Skonfiguruj środowisko Pythona
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Utwórz wirtualne środowisko i zainstaluj zależności
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Wykonaj testy
    - name: Run Tests
      run: |
        echo "Run tests"

    # 5. Zbuduj obraz Dockera
    - name: Build Docker image
      run: docker build -t flask-app:latest .
